// Generated by CoffeeScript 1.6.3
(function() {
  var AccessWithGeo, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AccessWithGeo = (function(_super) {
    var run;

    __extends(AccessWithGeo, _super);

    function AccessWithGeo() {
      _ref = AccessWithGeo.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    run = function() {};

    return AccessWithGeo;

  })(Program);

}).call(this);

/*
//@ sourceMappingURL=accessWithGeo.map
*/
