// Generated by CoffeeScript 1.6.3
(function() {
  (function(ws) {
    var WshShell, arch, arg, args, callAndWait, cmd, correctArch, i, isCScriptUsed, len, sr;
    callAndWait = function(execStr) {
      var TextStream, oExec;
      oExec = WshShell.Exec(execStr);
      TextStream = oExec.StdOut;
      while (oExec.Status === 0) {
        while (!TextStream.AtEndOfStream) {
          ws.Echo(TextStream.ReadLine());
        }
      }
    };
    WshShell = WScript.CreateObject("WScript.Shell");
    arch = WshShell.ExpandEnvironmentStrings("%PROCESSOR_ARCHITECTURE%");
    cmd = "cscript.exe //nologo \"" + ws.scriptFullName + "\"";
    correctArch = true;
    if (arch.indexOf("86") < 0) {
      sr = WshShell.ExpandEnvironmentStrings("%SystemRoot%");
      cmd = sr + "\\SysWOW64\\" + cmd;
      correctArch = false;
    }
    args = ws["arguments"];
    i = 0;
    len = args.length;
    while (i < len) {
      arg = args(i);
      cmd += " " + (~arg.indexOf(" ") ? "\"" + arg + "\"" : arg);
      i++;
    }
    isCScriptUsed = true || ws.fullName.slice(-12).toLowerCase() !== "\\cscript.exe";
    if (!correctArch || !isCScriptUsed) {
      callAndWait(cmd);
      return ws.quit();
    }
  })(WScript);

}).call(this);

/*
//@ sourceMappingURL=forceCorrectCScriptUse.map
*/
